#!/usr/bin/env python3
"""Generate bookends_nerdfont_names.lua from the bundled symbols.ttf.

We use the FONT'S OWN cmap glyph names rather than upstream
glyphnames.json — the JSON's labels disagree with the font's actual
glyphs for a meaningful fraction of codepoints (the font ships with
its own internal naming which is the authoritative source for what
renders at each codepoint).

Filter out entries whose font name is just a placeholder ("uni*",
"_NNN", "glyph*") with no meaningful label.

Usage:
    python3 tools/build_nerdfont_names.py \\
        --symbols-ttf /usr/lib/koreader/fonts/nerdfonts/symbols.ttf \\
        --output bookends_nerdfont_names.lua
"""

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    from fontTools.ttLib import TTFont
except ImportError:
    sys.exit("fontTools not installed. Run: pip install --user fonttools")


# Names that don't describe the glyph — generated placeholders the font
# tooling produces when no real label exists.
_PLACEHOLDER_PATTERNS = [
    re.compile(r"^uni[0-9A-Fa-f]{4,6}$"),    # uniE000, uniF1234
    re.compile(r"^u[0-9A-Fa-f]{4,6}$"),       # u1F600
    re.compile(r"^_\d+$"),                     # _445
    re.compile(r"^glyph\d+$"),                 # glyph123
    re.compile(r"^cid\d+$"),                   # cid567
    re.compile(r"^\.notdef$"),
]


def is_placeholder(name: str) -> bool:
    return any(p.match(name) for p in _PLACEHOLDER_PATTERNS)


def collect_named_codepoints(ttf_path: Path):
    """Return sorted list of (codepoint, name) pairs for all PUA-range glyphs
    in the font that have a meaningful (non-placeholder) glyph name."""
    f = TTFont(str(ttf_path))
    cmap = f.getBestCmap()
    out = []
    for cp, name in cmap.items():
        # Restrict to the font's PUA / private use area; skip ASCII-range
        # glyphs (like U+23FB POWER SYMBOL — those are standard Unicode
        # symbols already, no value in adding them to the picker).
        if cp < 0xE000:
            continue
        if is_placeholder(name):
            continue
        out.append((cp, name))
    out.sort(key=lambda nc: (nc[1].lower(), nc[0]))
    return out


def emit_lua(entries, output_path: Path, ttf_path: Path):
    when = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "-- Generated by tools/build_nerdfont_names.py — do not edit by hand.",
        f"-- Source font: {ttf_path}",
        "-- Glyph names taken from the font's own cmap (not upstream",
        "-- glyphnames.json — that JSON's labels disagree with the bundled",
        "-- font's actual glyphs for many codepoints).",
        f"-- Generated: {when}",
        "",
        f"-- Total entries: {len(entries)}",
        "",
        "local M = {",
    ]
    for cp, name in entries:
        # Quote-safe sanity check.
        if '"' in name or '\\' in name:
            raise ValueError(f"unexpected character in name: {name!r}")
        lines.append(f'    {{name="{name}", code=0x{cp:04X}}},')
    lines.append("}")
    lines.append("")
    lines.append("return M")
    lines.append("")
    output_path.write_text("\n".join(lines))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--symbols-ttf", type=Path,
                    default=Path("/usr/lib/koreader/fonts/nerdfonts/symbols.ttf"))
    ap.add_argument("--output", type=Path,
                    default=Path("bookends_nerdfont_names.lua"))
    args = ap.parse_args()

    if not args.symbols_ttf.exists():
        sys.exit(f"--symbols-ttf not found: {args.symbols_ttf}")

    entries = collect_named_codepoints(args.symbols_ttf)
    print(f"Named PUA glyphs in font: {len(entries)}")

    emit_lua(entries, args.output, args.symbols_ttf)
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
